### ISSUE TITLE
Can not correctly assign single & double escape peaks of the 2754-keV Na-24 peak

### ISSUE THREAD

**Issue by furutaka** [sandialabs/InterSpec#11]
Hi,

First of all, thank you very much for letting us use this software.  I really feel it's **the killer app** for analyzing gamma-ray spectra!
My problem is that I can not "assign" 2243- and 1732-keV peaks as the single and double escape peaks respectively of the 2754-keV gamma ray from Na-24 decay, either through "Peak Editor..." or "Change Nuclide".

I'm using InterSpec v.1.0.8, on Windows 10 (64-bit).

I'll attach a captured video.

Thanks,
Kazuyoshi Furutaka (JAEA)

https://user-images.githubusercontent.com/1713040/156702428-eba02ec4-ce2e-49c4-8feb-b5b0a69a23a0.mp4

**Comment by wcjohns** [comment]
Thank you very much for reporting this bug!
The detailed video was also quite helpful for tracing down the different code paths and testing them.

The basic problem was 511 or 1022 keV was being added to the full-energy gamma value, instead of to the fit-peak energy.  
This has been resolved, and the fix will be included in InterSpec v1.0.10.

In addition, commit 17326e60e449eccb277666b66ef71369bfe42a7f made the handling of nuclide assignments to peaks more consistent from any code paths that involved a string representation of the nuclide/x-ray/reaction being assigned (which in addition to the paths in this report, also includes from CSV/XML/N42 files, and a few other paths).

And btw, version 1.0.9 is available at https://github.com/sandialabs/InterSpec/releases/ 

Also, thank you very much for the kind words about the application - it is really great to know!
