### ISSUE TITLE
Incorrect absolute gamma ray emission probability for Th-227

### ISSUE THREAD

**Issue by jjwoodslbl** [sandialabs/InterSpec#20]
The absolute gamma ray emission probability for the 235.96 keV gamma ray in the decay of Th-227 is incorrect. It is listed as 0.356 and should be corrected to 0.12937 (J Environ. Radioact., 2016, 162, 358-370).

**Comment by wcjohns** [comment]
Thank you for finding and submitting this, and sorry it took a while to correct.

The 235.96 keV had been manually, and incorrectly, adjusted quite some time ago.  
However, additionally, all gammas for the Th227 parent were of by a factor of about 1.3565 due to an incorrect scale factor in the older version of ENDF we used as part of our initial creation of sandia.decay.xml.  These issue were fixed in [commit e2fb410b](https://github.com/sandialabs/SandiaDecay/commit/e2fb410b0ab4fae8c93f24ed3a56bb9f77b14593).

If you replace the `InterSpec/data/sandia.decay.xml` file in your current version of InterSpec, with the same file from the [SandiaDecay repo](https://github.com/sandialabs/SandiaDecay), you can pick up these changes.
Or if you are a Windows user, the latest bleeding edge build, has this change [here](https://github.com/sandialabs/InterSpec/releases/tag/latest).


Btw, a good url to compare branching ratios of different datasets is [at iaea.org](https://www-nds.iaea.org/exfor/servlet/E4sShowDecayData?db=e4&op=showDecayData&req=3313&Sect=8937092,9150214,14660924&plus=3).  From this link if you click the "+ Show all spectra" button, you can see the previous Th227 intensities (except 235.96 keV) were about equal to "ENDF/B-VIII.0" which are off by this factor of 1.3565 relative to JENDL-5/ENSDF-2021 (which are now about whats in sandia.decay.xml).

Thanks again for reporting this, and I also owe thanks to a Sandia colleague for figuring out what happened with the scale factor, and a LANL colleague for kindly providing a spectrum to validate the changes with.

**Comment by jjwoodslbl** [comment]
Thank you for your help!Josh On Feb 11, 2023, at 08:17, William Johnson ***@***.***> wrote:﻿
Thank you for finding and submitting this, and sorry it took a while to correct.
The 235.96 keV had been manually, and incorrectly, adjusted quite some time ago.
However, additionally, all gammas for the Th227 parent were of by a factor of about 1.3565 due to an incorrect scale factor in the older version of ENDF we used as part of our initial creation of sandia.decay.xml.  These issue were fixed in commit e2fb410b.
If you replace the InterSpec/data/sandia.decay.xml file in your current version of InterSpec, with the same file from the SandiaDecay repo, you can pick up these changes.
Or if you are a Windows user, the latest bleeding edge build, has this change here.
Btw, a good url to compare branching ratios of different datasets is at iaea.org.  From this link if you click the "+ Show all spectra" button, you can see the previous Th227 intensities (except 235.96 keV) were about equal to "ENDF/B-VIII.0" which are off by this factor of 1.3565 relative to JENDL-5/ENSDF-2021 (which are now about whats in sandia.decay.xml).
Thanks again for reporting this, and I also owe thanks to a Sandia colleague for figuring out what happened with the scale factor, and a LANL colleague for kindly providing a spectrum to validate the changes with.
