### ISSUE TITLE
MAC OS Problem

### ISSUE THREAD

**Issue by falcon2809** [sandialabs/InterSpec#21]
Hallo,

so i would like report a Problem under older MAC OS Versions. So i work under MAC OS 10.11 (El Captain). The latest Interspec Release 1.0.10 will be marked as not executable under the MAC OS Version. Without  any Problems only the [Initial Public Release] works fine.
INTERSPEC Version 1.0.5 and 1.0,6 open but only with a white Window Screen without any Menues (not usable). Version 1.0.7 opens but also with a white Window Screen , **BUT** at least there are an Menue, where you can open some Subfunctions. 
My Question is ; exist there some Add ON for the Operating System which must be installed for Interspec  or is it a Bug ?

Thank You for Help

Steffen Eckel

**Comment by wcjohns** [comment]
Hi Steffen,

This is likely an issue stemming from the difficulty (for me at least) of testing on older versions of macOS.

Some background: InterSpec is rendered using HTML + Javascript, and on macOS, it uses the OS provided WebView.

My guess for what is happening is that I've used some JavaScript that is not supported by the version of WebView on macOS 10.11, so an exception is happening, and things are not rendering.

I try to use JavaScript and macOS system calls that should support older versions of macOS, but obviously have probably missed something.

If you have Safari developer mode enabled (or are willing to enable it), you could inspect the InterSpec WebView from Safari (on recent macOS, from in Safari you go to the Develop menu, then a sub menu will list things running on your computer, and then from there you can select InterSpec) and see if it says the exception, or other error, that is happening.  I could then fix this.

Otherwise, for the next release I'll again to setup testing on an older version of macOS.

thanks for brining this to my attention,
  -will

**Comment by falcon2809** [comment]
Hallo Will,

first of all i`am really impressed how fast i got a feedback. Thank`s for that ; It is not an of course. 
I appreciate that. I should say i`am only an poor User not an Developer but i will try what i can to force my
Safari Version to "report" the Problem. I will tell you the Result so fast as possible.

Thank`s

Steffen

**Comment by falcon2809** [comment]
Hello William,

concerning "d (or are willing to enable it), you could inspect the InterSpec WebView from Safari " ..i tried but did not find :
"sub menu will list things running on your computer"  ......."and then from there you can select InterSpec"...not a single Word about Interspec. I also could not see than any Failure/Error Protocol.

Maybe i have to wait until next Release.

Thank You for Advise

Steffen

**Comment by wcjohns** [comment]
Hi Steffen,

Thanks for giving that a try!

It was a little bit of effort, but I managed to track down an install of El Capitan, and install it on an old mac.

The issue turns out to be that the WKWebView on macOS 10.11 doesn't support javascript statements like `let x = 2;` (i.e., ES6 or ECMAScript 2015); I had figured it would, since the latest versions of Safari for the OS does - but this is not the case.

Unfortunately, the InterSpec code uses a lot of these ES6 statements, so its not feasible to add support for the really old version of macOS - probably the oldest version of macOS the next release of InterSpec will support is 10.13 (High Sierra).

There is potentially another option, to use the "Electron" version of InterSpec, which from [here](https://www.electronjs.org/de/docs/latest/tutorial/unterstützung) looks to support macOS 10.11, although we don't normally make or test this build for macOS - perhaps send an email to InterSpec@sandia.gov and next time I happen to make a Electron build for macOS, I can send it to you as a no-promises something to try.

  -will

**Comment by wcjohns** [comment]
Hi,

I made a special one-off build of InterSpec that can run on El Capitan; you can find it at https://github.com/sandialabs/InterSpec/releases/tag/macOS_El_Cap_v1.0.11_rc3 

Seems to work okay, but there are a few downsides noted at the above url.

Let me know if it works for you,
  -will

**Comment by falcon2809** [comment]
Hi Will,

 

...i will try it this Weekend und give you a Feedback immediately after.

 

Thank you for your extraordinary Help for a small german Enthusiast
 

Steffen

 


 
 

Gesendet: Freitag, 17. März 2023 um 08:04 Uhr
Von: "William Johnson" ***@***.***>
An: "sandialabs/InterSpec" ***@***.***>
Cc: "falcon2809" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [sandialabs/InterSpec] MAC OS Problem (Issue #21)


 

Hi,

I made a special one-off build of InterSpec that can run on El Capitan; you can find it at https://github.com/sandialabs/InterSpec/releases/tag/macOS_El_Cap_v1.0.11_rc3

Seems to work okay, but there are a few downsides noted at the above url.

Let me know if it works for you,
-will

**Comment by falcon2809** [comment]
Hallo William,

 

i have tested your Release 1.0.11r3 over the Weekend. The first what was happend , after the first

start up of the App there was a white Board again.............oops, but than after a second boot up oft the Software it shows all,

like you describt, with a Menue inside the App-Window, but with all Functions which i expected.By the Way that`s not a big Issue.

 

I have tested nearly all Menue`s and Sub Menues the most of Tool Functions and also some Import/Export Functions without any 

Malfunction or Crash`s. Only teh CSV download was a litle bit confiusing cause i have to use the Excel CSV Export Function for an Complete

File which i could reimport than (only a Test).


 

My Backround is the Usage of the  :https://www.rhelectronics.store/nuclear-pioneer-mca-multichannel-analyzer-for-gamma-spectrometry

In the Attachement i show you my built of the MCA Unit based on Alex Nuclear Pioneer Boards and Firmware.

 

So i will use your Software as a primary Tool for deeper Inspection`s (AND LEARNING) of the MCA generated CSV Files. A nice Feature in this Context would be the Possibility

to show Live Data from the Unit via USB in Interspec. There are an Github Project to get this via GAMMA MCA from Phoenix 1747, but this are not a native 

Programm and a lot of Plattforms are restricted by the Browser Version`s AND there are not a REAL Offline Version like Interspec.

 

So that`s all for the Moment. Again THANK YOU VERY MUCH for your Engagement. I`am looking forward.

 

Steffen

 

 

 

Gesendet: Freitag, 17. März 2023 um 08:04 Uhr
Von: "William Johnson" ***@***.***>
An: "sandialabs/InterSpec" ***@***.***>
Cc: "falcon2809" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [sandialabs/InterSpec] MAC OS Problem (Issue #21)


 

Hi,

I made a special one-off build of InterSpec that can run on El Capitan; you can find it at https://github.com/sandialabs/InterSpec/releases/tag/macOS_El_Cap_v1.0.11_rc3

Seems to work okay, but there are a few downsides noted at the above url.

Let me know if it works for you,
-will

**Comment by wcjohns** [comment]
Thanks for letting me know it seems to work for you; I'm glad it does!

> Possibility to show Live Data from the Unit via USB in Interspec.

People, including myself a couple times, have used parts of InterSpec to make acquisition programs for detection systems - but including these capabilities into InterSpec is out-of-scope for a number of reasons (my InterSpec development is limited, I'm not convinced it would be a improvement to user experience generally, there are many different acquisition systems to support, etc).  Of course people are welcome to fork InterSpec, and I would be happy to provide reasonable accommodations or suggestions.

enjoy experimenting,
  -will
