### ISSUE TITLE
TestFlight for release candidates

### ISSUE THREAD

**Issue by tkerby** [sandialabs/InterSpec#25]
Would you consider releasing on TestFlight the latest release candidate for iOS? I'd be happy to beta test and have access to the newer features.

**Comment by wcjohns** [comment]
Hey Tim,

Due to time availability, I can't promise iOS or Android builds.

That being said, I did just enable a iOS public TestFlight group, and push the latest version of the code to it.

You should be able to access this via:
    https://testflight.apple.com/join/nY38egHO

However, please note that I didn't do anything more than confirm the app runs on my iPhone, and open a couple spectra - so there are likely to be plenty of issues (feel free to email InterSpec@sandia.gov with any you find).

There will be no "release candidate" builds for Android, and there may not even be final version builds every time for Android (its currently a real pain for me).

thanks,
  -will

**Comment by tkerby** [comment]
Thanks Will - much appreciated. Having mobile apps is so useful for the Radiacode. 

In terms of TestFlight, I'm getting an error saying the group isn't accepting new testers as below. Might need the number of users set or enabling public access via the link. 

![image](https://github.com/sandialabs/InterSpec/assets/3738500/b83ba7f9-d092-4574-aa02-ebda3abac3f9)

**Comment by ckuethe** [comment]
> There will be no "release candidate" builds for Android, and there may not even be final version builds every time for Android (its currently a real pain for me).

Automating android builds just crept up my holiday project list a few notches. I saw the docs for it, I see there's some docker pieces, I've been meaning to up my docker game anyway and having a fully dockerized process to build might be a worthy challenge.

**Comment by tkerby** [comment]
> Automating android builds just crept up my holiday project list a few notches. I saw the docs for it, I see there's some docker pieces, I've been meaning to up my docker game anyway and having a fully dockerized process to build might be a worthy challenge.

That's making me think I might be able to automate an iOS build too as GitHub actions supports building on Mac. Found quite a good guide at https://www.andrewhoog.com/post/how-to-build-an-ios-app-with-github-actions-2023/

**Comment by wcjohns** [comment]
Hi Tim - I hadn't set the number of Public Testers - I just did now - let me know if it works.

**Comment by tkerby** [comment]
Still getting the same error. I’ve found this checklist helpful in the past - https://help.playtestcloud.com/en/articles/6824982-resolving-the-this-beta-isn-t-accepting-any-new-testers-right-now-error#On 18 Dec 2023, at 20:13, William Johnson ***@***.***> wrote:﻿
Hi Tim - I hadn't set the number of Public Testers - I just did now - let me know if it works.

**Comment by wcjohns** [comment]
Hey Chris, 

I hadn't considered using Docker for the Android build - its a great idea!  

If you get it to work, I will be amazed.  Or else maybe I'll look into it for the next major version release.

But to warn you - the Android build of InterSpec, at least through Android Studio, is just absolutely terrible.  
Like really horrible, and there are always Android-specific problems in the InterSpec code.
Most of this is probably because I am not an Android developer, but I think its also due to such a large build through the NDK, and getting all the versions of build tools consistent (gradle, SDK, NDK, cmake, androidx, etc) seems like a challenge sometimes.

thanks Chris,
  -will

**Comment by wcjohns** [comment]
Thanks for the link Tim - it looks like things are still being processed on Apples side (approved, but with the yellow dot) - I'll check back in on it later today.

The automated build for iOS/macOS is on my TODO list (probably using Xcode Cloud), but honestly it will be a while before I can potentially find time to look into it.
  -will

**Comment by ckuethe** [comment]
The horrible android build experience sounds exactly like a docker use case; who cares how nasty the dependency chain is if all the pieces can be pinned and the build process runs in an isolated environment?

I do have a tiny bit experience with developer environments based on docker that allow a closer alignment between dev and prod, no matter what people use for their workstation OS. Alas, I've never had to try cross-build iOS apps from linux or windows.
