### ISSUE TITLE
Option "Ask to propagate peaks" works only once

### ISSUE THREAD

**Issue by BOPOHOP** [sandialabs/InterSpec#36]
MacOS sequoia, InterSpec v1.0.13 RC2.
Option "Ask to propagate peaks" works only once. It works again if it is turned off then on, but only once again.

**Comment by wcjohns** [comment]
Hi @BOPOHOP - thank you for reporting this.

I think this was part of a slightly larger problem of user preferences occasionally getting lost when syncing the in-memory preferences with the sqlite3 database on disk - and in v1.0.13 RC2, this frequency of losing things was increased to every ~1 minute, due to a timer that was added, but the underlying issue had been in InterSpec for quite a while, although only manifested more rarely under specific circumstances, so I was never really quite sure if it was actually happening, or when.  

Anyway, I believe commits 7cde4efcf59846d77bb2ecf5770661c2202e1a24 and f85b7136b4d2a960956831bc06c18871dae76339 should fix this issue.

I'll probably make a RC3 after some more testing myself, but otherwise I think its about ready for final release.

thanks again for reporting,
  -will
