### ISSUE TITLE
Al28 labeled as Mg28

### ISSUE THREAD

**Issue by lgordon** [sandialabs/InterSpec#37]
I'm not exactly sure if this an issue but seems to be labeled wrong:

![image](https://github.com/user-attachments/assets/dcd8fe65-e3b9-449c-92d8-59392ac9ded3)

**Comment by lgordon** [comment]
I think the parent column match the first element in the decay column, ie. Al28 in this case instead of Mg28? Also this energy 1778.85 doesn't correspond to 28Mg decay. 

You can also see the Al28 decay energy listed incorrectly when you search Mg28
![image](https://github.com/user-attachments/assets/639c1283-2d65-4afe-8ba4-ed916869f8bf)

**Comment by lgordon** [comment]
Thanks very much, I figured it was more likely I was misunderstanding. The spectra is from Al28 and shouldn't contain Mg28 but now I understand and it works as intended when you input the 0s.

**Comment by wcjohns** [comment]
A little bit of a re-vamp of the nuclide ID tab is planned, and I need to give it a little more thought, but I think it would be reasonable to have some sort of a "direct" or non-aged option, to help with situations similar to yours, or maybe kinda hint at meanings better - so thank you for creating the issue!

**Comment by wcjohns** [comment]
Hi, 

just to follow up: commit cabc14698bfa3785e86d175e8750335e99c75c2d adds in a "Un-aged Nuclides" option to the "Nuclide Search" tab.
This option does not decay the nuclides, but does the matching based on just the decay of the listed nuclide, not its progeny.

So for example, using this new option, if you search on 661.66 keV, you will get back a result of Ba137m, but NOT Cs137, since the 661.66 keV of a Cs137 source is actually from the Ba137m decay to Ba137, and not the Cs137 decay itself.

You can pick up an updated executable from the automated "bleeding edge" release at https://github.com/sandialabs/InterSpec/releases/tag/bleeding-edge
