### ISSUE TITLE
Detector response graph/fit not update when changeing shielding thickness

### ISSUE THREAD

**Issue by maluethi** [sandialabs/InterSpec#5]
Efficiency curves are not updated automatically when the thickness of the shielding is changed. The graph and the fit is correctly updated when any other setting is changed (taking into account the shielding).

**Comment by maluethi** [comment]
By the way great work, please keep up the good work! I like your tool a lot, especially looking at all other gamma spectroscopy software out there.

**Comment by wcjohns** [comment]
I'm really sorry I didnt seem to get a notification about this issue, and just now saw it.

I'm guessing this is in the "Make Detector Response" tool, and if so, it should be fixed by commit #50e2283d and will be included in the next release.

Thank you for reporting this issue, and the encouraging words!

**Comment by maluethi** [comment]
Thanks for fixing!
