### ISSUE TITLE
CSV files with only channels and data fail to open

### ISSUE THREAD

**Issue by f1ac** [sandialabs/InterSpec#7]
It seems there was a fix for this issue in a recent version of SpecUtils which is not referenced yet, https://github.com/sandialabs/SpecUtils/commit/8e528906709958572e739ce82403399c0e93540d

Currently headerless CSV files are interpreted as containing energy and data. Any kind of headers hinting that first column contains channel numbers fail to open:
![image](https://user-images.githubusercontent.com/13987066/116742865-acc14000-aa00-11eb-908d-c092cd221741.png)

**Comment by wcjohns** [comment]
Thank you for letting me know the version of SpecUtils referenced needed updated; this has been fixed in commit [sandialabs/InterSpec@072295c](https://github.com/sandialabs/InterSpec/commit/072295c8bda016d20b1abd79a9c48619f8fe2771).

It will also be included in the next release of InterSpec.

All the CSV formatted spectrum files we could find have been added to the regression test suite to keep this from happening in the future.
